env:
  JAVA_VERSION: '21'
jobs:
  verify:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Java
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ env.JAVA_VERSION }}
        website: jdk.java.net
    - continue-on-error: true
      if: runner.os == 'Linux'
      name: Run Tests (Linux)
      run: 'export DISPLAY=:90

        Xvfb -ac :90 -screen 0 1280x1024x24 > /dev/null 2>&1 &

        mvn clean verify checkstyle:checkstyle --no-transfer-progress -X

        '
    - continue-on-error: true
      if: runner.os != 'Linux'
      name: Run Tests (MacOS / Windows)
      run: 'mvn clean verify checkstyle:checkstyle --no-transfer-progress

        '
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
name: Scene Builder PR Verify
on:
  repository_dispatch:
    types: trigger-ga___build.yml
